language: cpp

dist: bionic

cache: apt

compiler:
    - gcc

env:
    global:
        - MAKEFLAGS="-j2"

before_script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir build && cd build && cmake ..; fi

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make; fi

os:
    - linux
    - windows

addons:
    apt:
        packages:
            - build-essential
            - cmake
            - libcapstone-dev
            - libgraphviz-dev
            - libqt5svg5-dev
            - libqt5xmlpatterns5-dev
            - pkg-config
            - qt5-default
            - qtbase5-dev
